config/routes.rb
Rails.application.routes.draw do
  post '/tinymce_assets' => 'tinymce_assets#create'
  resources :bills
  resources :codata
  resources :basedatas
  resources :saves
  resources :announces
  resources :events
  resources :activities
  # 活動報名，多的欄位
  post "store_TableRef" , :to =>"activities#store_TableRef"
  # 活動報名，
  get '/activities_detial(/:id)' , :to => "activities#activities_detial"
  get '/activities_detial' , :to => "activities#activities_detial"
  # 活動報名，excel
  #活動報名

  get 'del_activities' , :to => "activities#del_activities"
  get '/activities_success' , :to => "activities#activities_success"
  get '/activities_fail' , :to => "activities#activities_fail"
  #活動報名
  # get 'excel', :to => "activities#excel"
  get '/excel', :to => "activities#excel"
  get '/cate_about', :to => "cates#cate_about"


  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'

  get 'resumes/destroy'

  get 'attachments/:id'  => 'resumes#download'


  # get '*anything' => 'errors#routing_error'

  resources :footers
  mount Ckeditor::Engine => '/ckeditor'
  resources :cates
  resources :msgs
  # devise_for :users
  get '/user_list' , :to => "member#index"
  get '/user_create' , :to => "member#user_create"
  post "/member_create", :to => "member#member_create"
  get '/edit_service' , :to => "footers#edit_service"
  get '/edit_slug' , :to => "footers#edit_slug"
  get '/edit_aboutus' , :to => "footers#edit_aboutus"
  get "/edit_company/:id" => 'footers#edit_company'
  get "/about_company/:id" => 'home#about_company'
  get 'glossary' =>"home#glossary"
  get 'get_lng', :to => "home#get_lng"

  #home
  get '/' , :to => "home#index"
  get '/index' , :to => "home#index"
  get '/index2' , :to => "home#index2"

  get '/download' , :to => "home#download"
  get '/signup(/:id)' , :to => "home#signup"
  get '/news(/:cate_id)' , :to => "home#news"
  get '/news2(/:id)' , :to => "home#news2"
  get '/class_list', :to => "home#class_list"
  get '/service' , :to => "home#service"
  get '/contact' , :to => "home#contact"
  get '/about' , :to => "home#about"
  get '/event' , :to => "home#event"


  #json
  # get 'index_pm_json' ,:to => "home#index_pm_json"
  # get 'buttom_left_json' ,:to => "home#buttom_left_json"
  # get 'buttom_right_json' ,:to => "home#buttom_right_json"


  get 'safety_advice', :to => "home#safety_advice"
  #news
  get '/annos'     , :to => "home#annos"
  get '/anno'      , :to => "home#anno"

  #Application
  get '/application_main'     , :to => "home#application_main"
  get '/application_sub'     , :to => "home#application_sub"
  get '/application(/:id)'    , :to => "home#application"

  #產業
  get '/solutions_main'    , :to => "home#solutions_main"
  get '/solutions'    , :to => "home#solutions"
  #Company
  get '/company'    , :to => "home#company"
  get '/magnetism'    , :to => "home#magnetism"
  get '/magnetism2'    , :to => "home#magnetism2"

  #ajax
  post "ajax_msgs" , :to => "msgs#ajax_msgs"

  post "search" , :to => "home#search"
  post "/submit_signup" , :to => "home#submit_signup"
  post "/contact_submit" ,:to => "home#contact_submit"



  post "del_something" , :to =>"ajx#del_something"
  resources :products


  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  root "home#index"


  # CarrierWaveExample::Application.routes.draw do
  resources :bills
  resources :codata
  resources :bases
  resources :saves
  resources :announces
  resources :events
  # test
  get '/parse_xml' , :to => "home#parse_xml"
  get '/parse_xml2' , :to => "home#parse_xml2"
  # test
  resources :resumes, only: [:index, :new, :create, :destroy]
  #    root "resumes#index"
  # end

  # unless Rails.application.config.consider_all_requests_local
  #   # having created corresponding controller and action
  #   get '*not_found', to: 'errors#error_404'
  # end

  get 'aphp' ,:to => "home#aphp"

  namespace :api do
    namespace :v1 do
     resources :fruits, only: [:index, :create, :destroy, :update]
    end
  end


end

app/models/msg.rb
class Msg < ApplicationRecord
    paginates_per 12
    belongs_to :cate
    # belongs_to :user

    mount_uploader :img, ImageUploader
    # validates_processing_of :img

    
    # default_scope { order(sort: :desc) }

    # validates :title,   :presence => { :message => "標題-不能空白" } ,
    #                     :uniqueness => { :message => "標題-必填" }
    
end

app/controllers/msgs_controller.rb
class MsgsController < ApplicationController
  before_action :set_msg, only: [:show, :edit, :update, :destroy]
  before_action :set_title

  before_action :authenticate_user!  # 這個是 devise 提供的方法，先檢查必須登入
  before_action :authenticate_admin  # 再檢查是否有權限
  helper_method :sort_column, :sort_direction

  layout "bootstrap"
  # GET /msgs
  # GET /msgs.json
  def index
    @msgs = Msg.where.not(cate_id: [1]) .order(sort_column + " " + sort_direction).page(params[:page]).limit(12)
  end

  

  def ajax_msgs
    ids        = params[:ids]

    msgs      = Msg.where(cate_id: ids.split(",").map(&:to_i) )    

    html_data = ""
    html_data += "<br/>"
    msgs.each do |msg|      
      html_data += "<span style=\"margin:0px 0px 0px 19px;float: left;\" >"
      html_data += "<input type=\"checkbox\" name=\"ref[#{msg.id}]\" value=\"#{msg.id}\" > "
      html_data += "<font color=\"red\">#{msg.cate.name}</font>-"
      html_data += "#{msg.title} / #{msg.title_en}"
      html_data += "</span>"
    end

    html_data += "<br/>"

    render :text => "#{html_data}"
  end
  # GET /msgs/1
  # GET /msgs/1.json
  def show
  end

  # GET /msgs/new
  def new 
    @title    = ["Application(產品上架)","新增應用資訊"]           
    @msg      = Msg.new
  end

  # GET /msgs/1/edit
  def edit

    
    @title    = ["Application(產品上架)","編輯應用資訊"]
     
    
    
    @cate_id = @msg.cate_id

  end

  # POST /msgs
  # POST /msgs.json
  def create
    @msg = Msg.new(msg_params)

    # respond_to do |format|

      # @msg.user_id = current_user.id

      if @msg.save
        
        redirect_to action: "index"
        
        # format.html { redirect_to action: index , notice: 'Msg was successfully created.' }
        # format.json { render :show, status: :created, location: @msg }

      else
        format.html {render :new}
        format.json {render json: @msg.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /msgs/1
  # PATCH/PUT /msgs/1.json
  def update
    # respond_to do |format|

      # @msg.user_id = current_user.id

      if @msg.update(msg_params)

        
        redirect_to action: "index"
        
        # format.html { redirect_to msgs_url, notice: 'Msg was successfully updated.' }
        # format.json { render :show, status: :ok, location: @msg }
      else
        # format.html { 
          render :edit 
        # }
        # format.json { render json: @msg.errors, status: :unprocessable_entity }
      end
    # end
  end

  # DELETE /msgs/1
  # DELETE /msgs/1.json
  def destroy
    @msg.destroy

    respond_to do |format|
      format.html { redirect_to msgs_url, notice: 'Msg was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def sort_column
      Msg.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def set_msg
      @msg = Msg.find(params[:id])
    end

    def set_title

      @active = "msgs"
      @title = ["Application(產品上架)","列表"]
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def msg_params
      params.require(:msg).permit(:title, :title_en , :cate_id, :user_id, :content, :content_en ,:img , :sort)
    end
end

app/helpers/msgs_helper.rb
module MsgsHelper
end

app/views/msgs/_form.html.erb
<%= form_for(msg) do |f| %>
  <% if msg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(msg.errors.count, "error") %> prohibited this msg from being saved:</h2>

      <ul>
      <% msg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <style media="screen">
    .form-group label{
      font-size: 20px;
    }
  </style>

  <div class="form-group">
    <%= f.label :title , "標題-中文" %>
    <%= f.text_field :title , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title_en , "標題-英文" %>
    <%= f.text_field :title_en , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :sort , "排序" %>
    <%= f.text_field :sort , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :img,  "圖片" %><br>
    <%= f.file_field :img %>
    <% if f.object.img? %>
      <%= image_tag f.object.img.url %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :cate_id ,"應用分類"%>
    <%= f.select(:cate_id, Cate.all.map {|s| [s.name , s.id]}, { :selected => @cate_id} , class: "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :content,"內容-中文" %>
    <%= f.text_area :content ,id: "ckeditor", class: "tinymce"  %>
  </div>

 
 

  <div class="form-group">
    <%= f.label :content_en,"內容-英文" %>
    <%= f.text_area :content_en ,id: "ckeditor1", class: "tinymce" %>
  </div>

  <div class="form-group">
    <button class="btn btn-lg btn-primary" type="submit">確定</button>
  </div>
<% end %>

<script>
   tinymce.init({
     selector: '.tinymce',
     height: 500,
     menubar: true,
     plugins: [
       'advlist autolink lists link image charmap print preview anchor',
       'searchreplace visualblocks code fullscreen',
       'insertdatetime media table paste code help wordcount'
     ],
       toolbar: 'undo redo | formatselect | ' +
       ' bold italic backcolor | alignleft aligncenter ' +
       ' alignright alignjustify | bullist numlist outdent indent |' +
       ' removeformat | help'
   });
 </script>
 

app/views/msgs/edit.html.erb
<%= render 'form', msg: @msg %>

 

app/views/msgs/index.html.erb
<div class="table-responsive">
  <table class="table table-striped">
      <thead>
        <tr>
          <th>
            <%= sortable "id" ,'id' %>
          </th>
          <th>
            <%= sortable "title" ,'標題' %>
          </th>
          <th>
            <%= sortable "cate_id" ,'分類' %>
          </th>

          

          <th>
            圖片
          </th>
          <th>
            <%= sortable "sort" ,'排序' %>
          </th>
          <th>
            <%= sortable "content" ,'內容' %>
          </th>

          <th colspan="2">
            <%= link_to '新增應用資訊', new_msg_path , { class: "btn btn-success" ,:style=>'color:#FFFFFF;'} %>
          </th>
        </tr>
      </thead>

      <tbody>
        <% @msgs.each do |msg| %>
          <tr>
            <td><%= msg.id %></td>
            <td><%= msg.title %></td>
            <td>
              <% if msg.cate %>
                  <%= msg.cate.name %>
              <% end %>

            </td>
            <td><%= image_tag( msg.img , size: "70") if msg.img %></td>
            <td><%= msg.sort %></td>
            <td><%= get_str   msg.content %></td>

            <td><%= link_to '編輯', edit_msg_path(msg)  ,{  :class=>"btn btn-primary",:style=>'color:#FFFFFF;'} %></td>
            <td>


              <button type="button" id="<%=msg.id%>" name="button"
                class="btn btn-danger" >刪除</button>


            </td>
          </tr>
        <% end %>
      </tbody>

</table>


</div>



    <%= paginate @msgs , :theme => 'twitter-bootstrap-3'%>



<script type="text/javascript">
  $("document").ready(function(){



    $("button").click(function(){
      var r = confirm("確定要刪除嗎 !? ");

      if(r==true){

          // alert(  $(this).attr("id") );

          $.post("/del_something",{ "id" : $(this).attr("id"),
                                    "action_name" : "msgs" },function(data){
                                      // alert(data);
              if(data==1){

                alert("刪除成功");
                location.reload();

              }else if (data==2) {

              }
          });

      }else{

      }




    })


  });
</script>

app/views/msgs/new.html.erb
<%= render 'form', msg: @msg %>

 

app/views/msgs/show.html.erb
 
<p>
  <strong>Title:</strong>
  <%= @msg.title %>
</p>

<p>
  <strong>Cate:</strong>
  <%= @msg.cate_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @msg.content %>
</p>

<%= link_to 'Edit', edit_msg_path(@msg) %> |
<%= link_to 'Back', msgs_path %>