config/routes.rb
Rails.application.routes.draw do
  post '/tinymce_assets' => 'tinymce_assets#create'
  resources :bills
  resources :codata
  resources :basedatas
  resources :saves
  resources :announces
  resources :events
  resources :activities
  # 活動報名，多的欄位
  post "store_TableRef" , :to =>"activities#store_TableRef"
  # 活動報名，
  get '/activities_detial(/:id)' , :to => "activities#activities_detial"
  get '/activities_detial' , :to => "activities#activities_detial"
  # 活動報名，excel
  #活動報名

  get 'del_activities' , :to => "activities#del_activities"
  get '/activities_success' , :to => "activities#activities_success"
  get '/activities_fail' , :to => "activities#activities_fail"
  #活動報名
  # get 'excel', :to => "activities#excel"
  get '/excel', :to => "activities#excel"
  get '/cate_about', :to => "cates#cate_about"


  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'

  get 'resumes/destroy'

  get 'attachments/:id'  => 'resumes#download'


  # get '*anything' => 'errors#routing_error'

  resources :footers
  mount Ckeditor::Engine => '/ckeditor'
  resources :cates
  resources :msgs
  # devise_for :users
  get '/user_list' , :to => "member#index"
  get '/user_create' , :to => "member#user_create"
  post "/member_create", :to => "member#member_create"
  get '/edit_service' , :to => "footers#edit_service"
  get '/edit_slug' , :to => "footers#edit_slug"
  get '/edit_aboutus' , :to => "footers#edit_aboutus"
  get "/edit_company/:id" => 'footers#edit_company'
  get "/about_company/:id" => 'home#about_company'
  get 'glossary' =>"home#glossary"
  get 'get_lng', :to => "home#get_lng"

  #home
  get '/' , :to => "home#index"
  get '/index' , :to => "home#index"
  get '/index2' , :to => "home#index2"

  get '/download' , :to => "home#download"
  get '/signup(/:id)' , :to => "home#signup"
  get '/news(/:cate_id)' , :to => "home#news"
  get '/news2(/:id)' , :to => "home#news2"
  get '/class_list', :to => "home#class_list"
  get '/service' , :to => "home#service"
  get '/contact' , :to => "home#contact"
  get '/about' , :to => "home#about"
  get '/event' , :to => "home#event"


  #json
  # get 'index_pm_json' ,:to => "home#index_pm_json"
  # get 'buttom_left_json' ,:to => "home#buttom_left_json"
  # get 'buttom_right_json' ,:to => "home#buttom_right_json"


  get 'safety_advice', :to => "home#safety_advice"
  #news
  get '/annos'     , :to => "home#annos"
  get '/anno'      , :to => "home#anno"

  #Application
  get '/application_main'     , :to => "home#application_main"
  get '/application_sub'     , :to => "home#application_sub"
  get '/application(/:id)'    , :to => "home#application"

  #產業
  get '/solutions_main'    , :to => "home#solutions_main"
  get '/solutions'    , :to => "home#solutions"
  #Company
  get '/company'    , :to => "home#company"
  get '/magnetism'    , :to => "home#magnetism"
  get '/magnetism2'    , :to => "home#magnetism2"

  #ajax
  post "ajax_msgs" , :to => "msgs#ajax_msgs"

  post "search" , :to => "home#search"
  post "/submit_signup" , :to => "home#submit_signup"
  post "/contact_submit" ,:to => "home#contact_submit"



  post "del_something" , :to =>"ajx#del_something"
  resources :products


  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  root "home#index"


  # CarrierWaveExample::Application.routes.draw do
  resources :bills
  resources :codata
  resources :bases
  resources :saves
  resources :announces
  resources :events
  # test
  get '/parse_xml' , :to => "home#parse_xml"
  get '/parse_xml2' , :to => "home#parse_xml2"
  # test
  resources :resumes, only: [:index, :new, :create, :destroy]
  #    root "resumes#index"
  # end

  # unless Rails.application.config.consider_all_requests_local
  #   # having created corresponding controller and action
  #   get '*not_found', to: 'errors#error_404'
  # end

  get 'aphp' ,:to => "home#aphp"

  namespace :api do
    namespace :v1 do
     resources :fruits, only: [:index, :create, :destroy, :update]
    end
  end


end

app/models/announce.rb
class Announce < ApplicationRecord
	mount_uploader :img, ImageUploader
	# default_scope { order(sort: :desc) }
end

app/controllers/announces_controller.rb
class AnnouncesController < ApplicationController
  before_action :set_announce, only: [:show, :edit, :update, :destroy]
  before_action :set_title
  before_action :authenticate_user!  # 這個是 devise 提供的方法，先檢查必須登入
  before_action :authenticate_admin  # 再檢查是否有權限

  layout "bootstrap"
  # GET /announces
  # GET /announces.json
  def index
    @announces = Announce.all
  end

  # GET /announces/1
  # GET /announces/1.json
  def show
  end

  # GET /announces/new
  def new
    @announce = Announce.new
  end

  # GET /announces/1/edit
  def edit
  end

  # POST /announces
  # POST /announces.json
  def create
    @announce = Announce.new(announce_params)

    respond_to do |format|
      if @announce.save
        format.html { 
          # redirect_to :action "index", notice: 'Announce was successfully created.' 
          redirect_to action: "index"
        }
        # format.json { render :show, status: :created, location: @announce }
      else
        format.html { render :new }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announces/1
  # PATCH/PUT /announces/1.json
  def update
    respond_to do |format|
      if @announce.update(announce_params)
        format.html { 
          # redirect_to @announce, notice: 'Announce was successfully updated.' 
          redirect_to action: "index"
        }
        format.json { render :show, status: :ok, location: @announce }
      else
        format.html { render :edit }
        format.json { render json: @announce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announces/1
  # DELETE /announces/1.json
  def destroy
    @announce.destroy
    respond_to do |format|
      format.html { redirect_to announces_url, notice: 'Announce was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_title
      @active = "msgs"
      @title = ["永磁鐵",""]
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_announce
      @announce = Announce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announce_params
      params.require(:announce).permit(:title,:flag ,:title_en, :img, :content, :content_en ,:sort)
    end
end

app/helpers/announces_helper.rb
module AnnouncesHelper
end

app/views/announces/_form.html.erb
 

<%= form_for(announce) do |f| %>
  <% if announce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announce.errors.count, "error") %> prohibited this announce from being saved:</h2>

      <ul>
      <% announce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title,"中文標題" %>
    <%= f.text_field :title , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title_en ,"英文標題" %>
    <%= f.text_field :title_en , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :title_en ,"首頁是否顯示" %>
    <%= f.check_box :flag %>
  </div>
   

  

  <div class="form-group">
    <%= f.label :img,  "圖片" %><br>
    <%= f.file_field :img %>
    <% if f.object.img? %>
      <%= image_tag f.object.img.url %>      
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :sort , "排序" %>
    <%= f.text_field :sort , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content ,"中文內文" %>
    <%= f.text_area :content ,id: "ckeditor", class: "tinymce" %>
    
  </div>

  <div class="form-group">
    <%= f.label :content_en ,"英文內文"%>
    <%= f.cktext_area :content_en ,id: "ckeditor1", class: "tinymce" %>
    
  </div>

  <div class="form-group">
    <button class="btn btn-lg btn-primary" type="submit">確定</button>
  </div>
<% end %>


<script>
   tinymce.init({
     selector: '.tinymce',
     height: 500,
     menubar: true,
     plugins: [
       'advlist autolink lists link image charmap print preview anchor',
       'searchreplace visualblocks code fullscreen',
       'insertdatetime media table paste code help wordcount'
     ],
       toolbar: 'undo redo | formatselect | ' +
       ' bold italic backcolor | alignleft aligncenter ' +
       ' alignright alignjustify | bullist numlist outdent indent |' +
       ' removeformat | help'
   });
 </script>

app/views/announces/edit.html.erb
 
<%= render 'form', announce: @announce %>

<% link_to 'Show', @announce %> 
<% link_to 'Back', announces_path %>

app/views/announces/index.html.erb
<div class="table-responsive">
  <table class="table table-striped">
      <thead>
        <tr>
          <th>標題</th>      
          <th>圖片</th>
          <th>首頁是否顯示</th>      
          <th>排序</th>      
          <th colspan="2"><%= link_to '新增除鐵器', new_announce_path , { class: "btn btn-mg btn-success"  ,:style=>'color:#FFFFFF;'}%></th>
        </tr>
      </thead>

  <tbody>
    <% @announces.each do |announce| %>
      <tr>
        <td><%= announce.title %></td>        
        <td><%= image_tag( announce.img , size: "60") if announce.img %></td>
        <td><%=  raw (announce.flag.to_i == 1) ?  "<b style=color:blue>是</b>" : "<b style=color:red>否</b>" %></td>        
        <td><%= announce.sort %></td>        
        <td><%= link_to '編輯', edit_announce_path(announce) ,{ :class=>"btn btn-mg btn-primary",:style=>'color:#FFFFFF;'}%></td>
        <td><%= link_to '刪除', announce, { method: :delete, data: { confirm: 'Are you sure?' } , :class=>"btn btn-mg btn-danger" ,:style=>'color:#FFFFFF;' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/announces/new.html.erb
 
<%= render 'form', announce: @announce %>

<% link_to 'Back', announces_path %>

app/views/announces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @announce.title %>
</p>

<p>
  <strong>Title en:</strong>
  <%= @announce.title_en %>
</p>

<p>
  <strong>Img:</strong>
  <%= @announce.img %>
</p>

<p>
  <strong>Content:</strong>
  <%= @announce.content %>
</p>

<p>
  <strong>Content en:</strong>
  <%= @announce.content_en %>
</p>

<%= link_to 'Edit', edit_announce_path(@announce) %> 
<%= link_to 'Back', announces_path %>