config/routes.rb
Rails.application.routes.draw do
  post '/tinymce_assets' => 'tinymce_assets#create'
  resources :bills
  resources :codata
  resources :basedatas
  resources :saves
  resources :announces
  resources :events
  resources :activities
  # 活動報名，多的欄位
  post "store_TableRef" , :to =>"activities#store_TableRef"
  # 活動報名，
  get '/activities_detial(/:id)' , :to => "activities#activities_detial"
  get '/activities_detial' , :to => "activities#activities_detial"
  # 活動報名，excel
  #活動報名

  get 'del_activities' , :to => "activities#del_activities"
  get '/activities_success' , :to => "activities#activities_success"
  get '/activities_fail' , :to => "activities#activities_fail"
  #活動報名
  # get 'excel', :to => "activities#excel"
  get '/excel', :to => "activities#excel"
  get '/cate_about', :to => "cates#cate_about"


  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'

  get 'resumes/destroy'

  get 'attachments/:id'  => 'resumes#download'


  # get '*anything' => 'errors#routing_error'

  resources :footers
  mount Ckeditor::Engine => '/ckeditor'
  resources :cates
  resources :msgs
  # devise_for :users
  get '/user_list' , :to => "member#index"
  get '/user_create' , :to => "member#user_create"
  post "/member_create", :to => "member#member_create"
  get '/edit_service' , :to => "footers#edit_service"
  get '/edit_slug' , :to => "footers#edit_slug"
  get '/edit_aboutus' , :to => "footers#edit_aboutus"
  get "/edit_company/:id" => 'footers#edit_company'
  get "/about_company/:id" => 'home#about_company'
  get 'glossary' =>"home#glossary"
  get 'get_lng', :to => "home#get_lng"

  #home
  get '/' , :to => "home#index"
  get '/index' , :to => "home#index"
  get '/index2' , :to => "home#index2"

  get '/download' , :to => "home#download"
  get '/signup(/:id)' , :to => "home#signup"
  get '/news(/:cate_id)' , :to => "home#news"
  get '/news2(/:id)' , :to => "home#news2"
  get '/class_list', :to => "home#class_list"
  get '/service' , :to => "home#service"
  get '/contact' , :to => "home#contact"
  get '/about' , :to => "home#about"
  get '/event' , :to => "home#event"


  #json
  # get 'index_pm_json' ,:to => "home#index_pm_json"
  # get 'buttom_left_json' ,:to => "home#buttom_left_json"
  # get 'buttom_right_json' ,:to => "home#buttom_right_json"


  get 'safety_advice', :to => "home#safety_advice"
  #news
  get '/annos'     , :to => "home#annos"
  get '/anno'      , :to => "home#anno"

  #Application
  get '/application_main'     , :to => "home#application_main"
  get '/application_sub'     , :to => "home#application_sub"
  get '/application(/:id)'    , :to => "home#application"

  #產業
  get '/solutions_main'    , :to => "home#solutions_main"
  get '/solutions'    , :to => "home#solutions"
  #Company
  get '/company'    , :to => "home#company"
  get '/magnetism'    , :to => "home#magnetism"
  get '/magnetism2'    , :to => "home#magnetism2"

  #ajax
  post "ajax_msgs" , :to => "msgs#ajax_msgs"

  post "search" , :to => "home#search"
  post "/submit_signup" , :to => "home#submit_signup"
  post "/contact_submit" ,:to => "home#contact_submit"



  post "del_something" , :to =>"ajx#del_something"
  resources :products


  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  root "home#index"


  # CarrierWaveExample::Application.routes.draw do
  resources :bills
  resources :codata
  resources :bases
  resources :saves
  resources :announces
  resources :events
  # test
  get '/parse_xml' , :to => "home#parse_xml"
  get '/parse_xml2' , :to => "home#parse_xml2"
  # test
  resources :resumes, only: [:index, :new, :create, :destroy]
  #    root "resumes#index"
  # end

  # unless Rails.application.config.consider_all_requests_local
  #   # having created corresponding controller and action
  #   get '*not_found', to: 'errors#error_404'
  # end

  get 'aphp' ,:to => "home#aphp"

  namespace :api do
    namespace :v1 do
     resources :fruits, only: [:index, :create, :destroy, :update]
    end
  end


end

app/models/cate.rb
class Cate < ApplicationRecord

  mount_uploader :img, ImageUploader
  validates_processing_of :img
  # default_scope { order(level: :desc) }
  # has_many  :footer
  # validates :name,   :presence => { :message => "名稱-不能空白" }
  # validates :name,   :uniqueness => { :message => "名稱-必填" }

end

app/controllers/cates_controller.rb
class CatesController < ApplicationController
  before_action :set_cate, only: [:show, :edit, :update, :destroy]
  before_action :set_title
  before_action :authenticate_user!  # 這個是 devise 提供的方法，先檢查必須登入
  before_action :authenticate_admin  # 再檢查是否有權限
  # before_action :authenticate_level_99
  layout "bootstrap"
  # GET /cates
  # GET /cates.json
  def index
    # self.authenticate_level_99
    @cates = Cate.where.not(:id => 1).order(sort_column + " " + sort_direction).page(params[:page]).limit(8)
    @level = 1
  end

  def cate_about
    @cates = Cate.where(:level =>2).where.not("name like '%NO%'").order(sort_column + " " + sort_direction).page(params[:page]).limit(8)
    # @cates = @cates.where.not("name like '%NO%'")
    @title = ["Application(類別)","列表"]
    @level = 2
    render "index"
  end

  # GET /cates/1
  # GET /cates/1.json
  def show
  end

  # GET /cates/new
  def new
    @title = ["Application(類別)","新增產品分類"]
    @level = params[:level]
    @level_count = 2
    @cate = Cate.new
  end

  # GET /cates/1/edit
  def edit
    @title = ["Application(類別)","編輯產品分類"]
    @level = params[:level]
  end

  # POST /cates
  # POST /cates.json
  def create
    @cate = Cate.new(cate_params)

    respond_to do |format|
      if @cate.save
        format.html {
          # if @cate.level.to_i == 1
            redirect_to action: "index"
          # elsif @cate.level.to_i == 2
          #   Footer.create( :cate_id=>@cate.id , :title_ch =>@cate.name)
          #   redirect_to action: "cate_about"
          # end
        }
        format.json { render :show, status: :created, location: @cate }
      else
        format.html { render :new }
        format.json { render json: @cate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cates/1
  # PATCH/PUT /cates/1.json
  def update
    respond_to do |format|
      if @cate.update(cate_params)
        format.html {
          # if @cate.level.to_i == 1
            redirect_to action: "index"
          # elsif @cate.level.to_i == 2

          #   redirect_to action: "cate_about"
          # end
        }
        # format.html { redirect_to cates_url, notice: 'Cate was successfully updated.' }
        # format.json { render :show, status: :ok, location: @cate }
      else
        format.html { render :edit }
        format.json { render json: @cate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cates/1
  # DELETE /cates/1.json
  def destroy
    @cate.destroy
    respond_to do |format|
      format.html { redirect_to action: 'index', notice: 'Cate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def sort_column
      Cate.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_cate
      @cate = Cate.find(params[:id])
    end

    def set_title
      @active = "cates"
      @title = ["Application(類別)","列表"]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cate_params
      params.require(:cate).permit(:name , :flag , :level , :ref_cate_id , :name_en ,:content ,:content_en, :img)
    end
end

app/helpers/cates_helper.rb
module CatesHelper
end

app/views/cates/_form.html.erb
<%= tinymce %>

<%= form_for(cate) do |f| %>
  <% if cate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cate.errors.count, "error") %> prohibited this cate from being saved:</h2>

      <ul>
      <% cate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name ,"中文名稱" %>
    <%= f.text_field :name, class: "form-control"  %>

  </div>


  <div class="form-group">
    <%= f.label :name_en ,"英文名稱" %>
    <%= f.text_field :name_en, class: "form-control"  %>
  </div>

   <div class="form-group">
    <%= f.label :name_en ,"首頁是否顯示" %>
    <%= f.check_box :flag %>
  </div>


  <div class="form-group">
    <%= f.label :level ,"排序" %>
    <%= f.text_field :level, class: "form-control"  %>
  </div>


  <div class="form-group">
    <%= f.label :img,  "圖片" %><br>
    <%= f.file_field :img %>
    <% if f.object.img? %>
      <%= image_tag f.object.img.url %>
      <%= f.label :remove_img %>
      <%= f.check_box :remove_img %>
    <% end %>
  </div>


  <div class="form-group">

    <h3 class="sub-header"><%= f.label :content,"產品內容-中文" %></h3>
    <%= f.text_area :content ,id: "ckeditor", class: "tinymce" %>
  </div>

  <div class="form-group">
    <h2 class="sub-header"><%= f.label :content_en,"產品內容-英文" %></h3>
    <%= f.text_area :content_en ,id: "ckeditor1", class: "tinymce" %>
  </div>



  



  <div class="form-group ref_cate_id" style="display:none;">
    <%= f.label :ref_cate_id ,"" %>
    <%= f.text_field :ref_cate_id, class: "form-control"  %>
  </div>

  <div class="form-group">

    <button class="btn btn-lg btn-primary" type="submit">確定</button>
  </div>
<% end %>


 
<script>
   tinymce.init({
     selector: '.tinymce',
     height: 500,
     menubar: false,
     plugins: [
       'advlist autolink lists link image charmap print preview anchor',
       'searchreplace visualblocks code fullscreen',
       'insertdatetime media table paste code help wordcount'
     ],
       toolbar: 'undo redo | formatselect | ' +
       ' bold italic backcolor | alignleft aligncenter ' +
       ' alignright alignjustify | bullist numlist outdent indent |' +
       ' removeformat | help'
   });
 </script>

app/views/cates/edit.html.erb
<%= render 'form', cate: @cate  ,level: @level %>

<%  link_to 'Show', @cate %>
<%  link_to 'Back', cates_path %>

app/views/cates/index.html.erb
<div class="table-responsive">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>名稱</th>
      <th>排序</th>
      <th>首頁是否顯示</th>      
      <th>圖片</th>
      <th>
      <%= link_to '新增應用分類', new_cate_path , { class: "btn btn-mg btn-success"  ,:style=>'color:#FFFFFF;'} %>
      </th>
    </tr>
  </thead>

  <tbody>
    <% @cates.each do |cate| %>
      <tr>
        <td><%= cate.name %></td>
        <td><%= cate.level %></td>
        <td><%=raw   (cate.flag.to_i == 1) ? "<b style=color:blue>是</b>" : "<b style=color:red>否</b>" %></td>        
        <td><%= image_tag( cate.img , size: "60") if cate.img %></td>
        <td>

          <%= link_to '編輯', edit_cate_path(:id=>cate.id)  ,{ :class=>"btn btn-mg btn-primary",:style=>'color:#FFFFFF;'} %>
          <%= link_to '新增應用資訊', new_msg_path(:cate_id=>cate.id ) , {class: "btn btn-mg btn-info" ,:style=>'color:#FFFFFF;'} %>
        
          <button type="button" id="<%=cate.id%>" name="button"
            class="btn btn-mg btn-danger" >刪除</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


    <%= paginate @cates , :theme => 'twitter-bootstrap-3'%>


</div>



<script type="text/javascript">
  $("document").ready(function(){



    $("button").click(function(){
      var r = confirm("確定要刪除嗎 !? ");

      if(r==true){

          // alert(  $(this).attr("id") );

          $.post("/del_something",{ "id" : $(this).attr("id"),
                                    "action_name" : "cates" },function(data){
                                      // alert(data);
              if(data==1){

                alert("刪除成功");
                location.reload();

              }else if (data==2) {

              }
          });

      }else{

      }




    })


  });
</script>

app/views/cates/new.html.erb
<%= render 'form', cate: @cate ,level: @level %>

app/views/cates/show.html.erb
 
<p>
  <strong>Name:</strong>
  <%= @cate.name %>
</p>

<%= link_to 'Edit', edit_cate_path(@cate) %> |
<%= link_to 'Back', cates_path %>