config/routes.rb
Rails.application.routes.draw do
  post '/tinymce_assets' => 'tinymce_assets#create'
  resources :bills
  resources :codata
  resources :basedatas
  resources :saves
  resources :announces
  resources :events
  resources :activities
  # 活動報名，多的欄位
  post "store_TableRef" , :to =>"activities#store_TableRef"
  # 活動報名，
  get '/activities_detial(/:id)' , :to => "activities#activities_detial"
  get '/activities_detial' , :to => "activities#activities_detial"
  # 活動報名，excel
  #活動報名

  get 'del_activities' , :to => "activities#del_activities"
  get '/activities_success' , :to => "activities#activities_success"
  get '/activities_fail' , :to => "activities#activities_fail"
  #活動報名
  # get 'excel', :to => "activities#excel"
  get '/excel', :to => "activities#excel"
  get '/cate_about', :to => "cates#cate_about"


  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'

  get 'resumes/destroy'

  get 'attachments/:id'  => 'resumes#download'


  # get '*anything' => 'errors#routing_error'

  resources :footers
  mount Ckeditor::Engine => '/ckeditor'
  resources :cates
  resources :msgs
  # devise_for :users
  get '/user_list' , :to => "member#index"
  get '/user_create' , :to => "member#user_create"
  post "/member_create", :to => "member#member_create"
  get '/edit_service' , :to => "footers#edit_service"
  get '/edit_slug' , :to => "footers#edit_slug"
  get '/edit_aboutus' , :to => "footers#edit_aboutus"
  get "/edit_company/:id" => 'footers#edit_company'
  get "/about_company/:id" => 'home#about_company'
  get 'glossary' =>"home#glossary"
  get 'get_lng', :to => "home#get_lng"

  #home
  get '/' , :to => "home#index"
  get '/index' , :to => "home#index"
  get '/index2' , :to => "home#index2"

  get '/download' , :to => "home#download"
  get '/signup(/:id)' , :to => "home#signup"
  get '/news(/:cate_id)' , :to => "home#news"
  get '/news2(/:id)' , :to => "home#news2"
  get '/class_list', :to => "home#class_list"
  get '/service' , :to => "home#service"
  get '/contact' , :to => "home#contact"
  get '/about' , :to => "home#about"
  get '/event' , :to => "home#event"


  #json
  # get 'index_pm_json' ,:to => "home#index_pm_json"
  # get 'buttom_left_json' ,:to => "home#buttom_left_json"
  # get 'buttom_right_json' ,:to => "home#buttom_right_json"


  get 'safety_advice', :to => "home#safety_advice"
  #news
  get '/annos'     , :to => "home#annos"
  get '/anno'      , :to => "home#anno"

  #Application
  get '/application_main'     , :to => "home#application_main"
  get '/application_sub'     , :to => "home#application_sub"
  get '/application(/:id)'    , :to => "home#application"

  #產業
  get '/solutions_main'    , :to => "home#solutions_main"
  get '/solutions'    , :to => "home#solutions"
  #Company
  get '/company'    , :to => "home#company"
  get '/magnetism'    , :to => "home#magnetism"
  get '/magnetism2'    , :to => "home#magnetism2"

  #ajax
  post "ajax_msgs" , :to => "msgs#ajax_msgs"

  post "search" , :to => "home#search"
  post "/submit_signup" , :to => "home#submit_signup"
  post "/contact_submit" ,:to => "home#contact_submit"



  post "del_something" , :to =>"ajx#del_something"
  resources :products


  devise_for :users , :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # devise_for :users, controllers: { omniauth_callbacks: "callbacks" }
  root "home#index"


  # CarrierWaveExample::Application.routes.draw do
  resources :bills
  resources :codata
  resources :bases
  resources :saves
  resources :announces
  resources :events
  # test
  get '/parse_xml' , :to => "home#parse_xml"
  get '/parse_xml2' , :to => "home#parse_xml2"
  # test
  resources :resumes, only: [:index, :new, :create, :destroy]
  #    root "resumes#index"
  # end

  # unless Rails.application.config.consider_all_requests_local
  #   # having created corresponding controller and action
  #   get '*not_found', to: 'errors#error_404'
  # end

  get 'aphp' ,:to => "home#aphp"

  namespace :api do
    namespace :v1 do
     resources :fruits, only: [:index, :create, :destroy, :update]
    end
  end


end

app/models/activity.rb
class Activity < ApplicationRecord


  # def self.to_csv(options = {})
  #   desired_columns = ["id", "title","date","time"]
  #    CSV.generate(options) do |csv|
  #        csv << desired_columns
  #        all.each do |product|
  #          csv << product.attributes.values_at(*desired_columns)
  #        end
  #    end
  # end
  validates_format_of :date, :with => /\d{4}\-\d{2}\-\d{2}/, :message => "西元年-月-日"
  validates :date,  :presence => { :message => "日期-不能空白" } ,
                     :uniqueness => { :message => "日期-必填" }
  validates :time,  :presence => { :message => "時間-不能空白" } ,
                    :uniqueness => { :message => "時間-必填" }
  validates :title,  :presence => { :message => "活動標題-不能空白" } ,
                     :uniqueness => { :message => "活動標題-必填" }
  validates :content,  :presence => { :message => "活動內容-不能空白" } ,
                    :uniqueness => { :message => "活動內容-必填" }
  validates :limit_user,  :presence => { :message => "人數上限-不能空白" } ,
                    :uniqueness => { :message => "人數上限-必填" }

  # devise 	 :omniauthable


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :set_title
  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  layout "bootstrap"

  # GET /activities
  # GET /activities.json
  def index
    #qweqweqwe
    @activities = Activity.order(sort_column + " " + sort_direction).page(params[:page]).limit(12)
    # @activities.destroy_all
  end

  def excel

    @products = Activity.find(params[:id])
    #如果有額外的欄位
    # if !@products.other_table_name.nil?
    sql = "select * from `other_#{@products.other_table_name}`"

    # @records_array = ActiveRecord::Base.connection.execute(sql)

    @connection = ActiveRecord::Base.connection
    @esult = @connection.exec_query(sql)
    # end

    respond_to do |format|
      format.html
      # format.csv { send_data @products.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end


  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end


  def store_field

  end
  # POST /activities
  # POST /activities.json
  def create

    @activity = Activity.new(activity_params)



    # @connection = ActiveRecord::Base.connection
    # result = @connection.exec_query('select tablename from system.tables')


    # render :json => @activity.to_json

    # respond_to do |format|
      if @activity.save
        #如果欄位還有大於1
        random_table_name = (0...8).map { (65 + rand(26)).chr }.join
        @activity.other_table_name = random_table_name
        @activity.save





        if !@activity.column_num.nil? && @activity.column_num.to_i > 0
              # redirect_to :action => "add_a_column"
              # render :add_a_column
              # redirect_to(:action => "index" )and return if @activity.nil?


              render :action => "add_a_column" , :locals => { :activity => @activity.column_num }

              # return redirect_to("add_a_column")
        else

            #欄位為0
            _sql = "CREATE TABLE `other_#{@activity.other_table_name}` ( " +
                    " `id` int(11) NOT NULL AUTO_INCREMENT, " +
                    " `name` varchar(255) DEFAULT NULL, "+
                    " `sex` varchar(255) DEFAULT NULL, "+
                    " `phone` varchar(255) DEFAULT NULL, "+
                    " `birthday` date DEFAULT NULL, "+
                    " `address` varchar(255) DEFAULT NULL, "+
                    " `email` varchar(255) DEFAULT NULL, "+
                    " `user_content` text DEFAULT NULL, "+
                    " `admin_content` text DEFAULT NULL, "+
                    " `act_flag` int(1) DEFAULT NULL, "+
                    " `created_at` datetime NOT NULL, "+
                    " `updated_at` datetime NOT NULL, "+
                    " PRIMARY KEY (`id`) "+
                    " ) ENGINE=InnoDB DEFAULT CHARSET=utf8; "

            @connection = ActiveRecord::Base.connection
            @esult = @connection.exec_query(_sql)
            redirect_to action: "index"
            # format.html {
              # redirect_to @activity
              # , notice: 'Activity was successfully created.' }
            # format.json { render :show, status: :created, location: @activity }
        end


        # redirect_back(fallback_location: "activities")

      else
      # else
        render :new
        # format.json { render json: @product.errors, status: :unprocessable_entity }
      # end
      #   redirect_to action: "index"
        # format.html { render :new }
        # format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    # end
  end

  def add_a_column
      render "add_a_column"
  end


  def activities_success

    activ=Activity.find(params[:activity_id])


    sql = "update `other_#{activ.other_table_name}` set `admin_content` = '核准報名', `act_flag` = '1' where `id` = '#{params[:id]}' "
    connection = ActiveRecord::Base.connection
    connection.exec_query(sql)

    redirect_to controller: 'activities', action: 'activities_detial', id: params[:activity_id]
  end

  def activities_fail

    activ=Activity.find(params[:activity_id])


    sql = "update `other_#{activ.other_table_name}` set `admin_content` = '取消報名', `act_flag` = '0' where `id` = '#{params[:id]}' "
    connection = ActiveRecord::Base.connection
    connection.exec_query(sql)
    redirect_to controller: 'activities', action: 'activities_detial', id: params[:activity_id]

  end


  def activities_detial
    #找到相關的TABLE

    @activ=Activity.find(params[:id])
    @activ.other_table_name
    sql = "select * from `other_#{@activ.other_table_name}`"
    # @records_array = ActiveRecord::Base.connection.execute(sql)

    @connection = ActiveRecord::Base.connection
    @esult = @connection.exec_query(sql)

    @title = ["活動報名","#{@activ.title}-活動報名報名人員列表"]
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json

  #刪除資料庫
  def del_activities

    @activity = Activity.find(params[:id])
    sql = "drop table `other_#{@activity.other_table_name}` "
    connection = ActiveRecord::Base.connection
    connection.exec_query(sql)
    @activity.destroy

    redirect_to controller: 'activities', action: 'index', notice: "刪除成功！！！"
  end

  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  # 建立多欄位&資料庫
  def store_TableRef
      activity_fields = ""
      sql_fields = ""
      field_count = 0

      request.request_parameters[:field].each do |name , val |
        #將欄位存成JSON到MYSQL
        if request.request_parameters[:field].count.to_i == 1

              activity_fields += '"'+"#{name}"+'":"'+ "#{val}"+'"'

        else

            if field_count == 0
              activity_fields += '"'+"#{name}"+'":"'+ "#{val}"+'"'
            else
              activity_fields += ', "'+"#{name}"+'":"'+ "#{val}"+'"'
            end

        end

        sql_fields += " `#{name}` varchar(255) DEFAULT NULL, "
        field_count += 1
      end



      activity_fields = "{#{activity_fields}}"

      # render :text=>"#{fields} <br>#{request.request_parameters}"

      activity_id = request.request_parameters[:activity_id]
      acti = Activity.find(activity_id)
      acti.column_detail = activity_fields
      acti.save

      _sql = "CREATE TABLE `other_#{request.request_parameters[:table_name]}` ( " +
              " `id` int(11) NOT NULL AUTO_INCREMENT, " +
              " #{sql_fields} " +
              " `name` varchar(255) DEFAULT NULL, "+
              " `sex` varchar(255) DEFAULT NULL, "+
              " `phone` varchar(255) DEFAULT NULL, "+
              " `birthday` date DEFAULT NULL, "+
              " `address` varchar(255) DEFAULT NULL, "+
              " `email` varchar(255) DEFAULT NULL, "+
              " `user_content` text DEFAULT NULL, "+
              " `admin_content` text DEFAULT NULL, "+
              " `act_flag` int(1) DEFAULT NULL, "+
              " `created_at` datetime NOT NULL, "+
              " `updated_at` datetime NOT NULL, "+
              " PRIMARY KEY (`id`) "+
              " ) ENGINE=InnoDB DEFAULT CHARSET=utf8; "

      @connection = ActiveRecord::Base.connection
      @esult = @connection.exec_query(_sql)
      redirect_to action: "index"
      # @trf = TableRef.new()
      # @trf.activite_id = @activity.id
      # @trf.table_name = "ta"
      # @trf.column_name = "cn"
      # @trf.name = "name"
      # @trf.save

  end

  private

    def sort_column
      Activity.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end








    def set_title

      @active = "activities"
      @title = ["活動報名","列表"]
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:date, :time, :title,:title_en, :content , :content_en, :limit_user, :other_table_name , :column_num)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper

  def join_other_table_ok table_name


     sql = "show tables like 'other_#{table_name}'; "

     # @records_array = ActiveRecord::Base.connection.execute(sql)

     connection = ActiveRecord::Base.connection
     return esult = connection.exec_query(sql)
  end

  def query_talbe table_name


     e_sql = "select count(*) from `other_#{table_name}` ; "

     # @records_array = ActiveRecord::Base.connection.execute(sql)

     connection = ActiveRecord::Base.connection
     return esult = connection.exec_query(e_sql)
  end

end

app/views/activities/_form.html.erb
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/hot-sneaks/jquery-ui.css" rel="stylesheet">
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js"></script>

<%= form_for(activity) do |f| %>
<% if activity.errors.any? %>

  <div id="error_explanation">

    <h2><%= pluralize(activity.errors.count, "error") %>以下為必填，或是格式不符合</h2>

    <ul>
    <% activity.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>

<% end %>

  <style media="screen">
    .form-group label{
      font-size: 20px;
    }
  </style>

  <div class="form-group">
    <%= f.label :date , "日期" %>  <font style="color:red;margin-left:30px;">請使用日期格式 , 例如 : 2016-01-01</font>
    <%= f.text_field :date , class: "form-control date" ,id: "datepicker1" %>
  </div>

  <div class="form-group">
    <%= f.label :time ,"時間"%>
    <%= f.time_select :time , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :title,"活動名稱-中文" %>
    <%= f.text_field :title , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :title_en,"活動名稱-英文" %>
    <%= f.text_field :title_en , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :content ,"活動內容-中文"%>
    <%= f.text_area :content ,  id: "ckeditor"  %>
  </div>

  <div class="form-group">
    <%= f.label :content_en ,"活動內容-英文"%>
    <%= f.text_area :content_en , class: "form-control ckeditor cke" ,id: "ckeditor"%>
  </div>

  <div class="form-group">
    <%= f.label :limit_user,"人數上限" %>
    <%= f.number_field :limit_user, class: "form-control" %>
  </div>


  <% if activity.id.nil?  %>
  <div class="form-group">
    <%= f.label :column_num , "額外欄位數目(個)" %>
    <%= f.number_field :column_num , class: "form-control"%>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

<script type="text/javascript">

$(document).ready( function(){



  $('#ckeditor').each(function() {
    CKEDITOR.replace($(this).attr('id'));
  });


  var opt={
   dayNames:["星期日","星期一","星期二","星期三","星期四","星期五","星期六"],
   dayNamesMin:["日","一","二","三","四","五","六"],
   monthNames:["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
   monthNamesShort:["一月","二月","三月","四月","五月","六月","七月","八月","九月","十月","十一月","十二月"],
   prevText:"上月",
   nextText:"次月",
   weekHeader:"週",
   showMonthAfterYear:true,
   dateFormat:"yy-mm-dd"
   };
   $("#datepicker1").datepicker(opt);
   $("#datepicker1").reload();
   location.reload();

});


</script>

app/views/activities/activities_detial.html.erb
<div class="table-responsive">
  <table class="table table-striped">

  <thead>
    <tr>
      <th>
        姓名
      </th>
      <th>
        姓別
      </th>
      <th>
        電話
      </th>
      <th>
        住址
      </th>
      <th>
        E-MAIL
      </th>
      <% if !@activ.column_detail.nil?  %>
        <% cdjs =JSON.parse( @activ.column_detail )%>
        <% cdjs.each do |text_name,label_name| %>
          <th>
            <%=label_name%>
          </th>
        <% end %>
      <% end %>

      <td>
        狀態
      </td>
      
      <th>

      </th>



    </tr>
  </thead>

  <tbody>
  <%  @esult.each do |aa| %>
    <tr>
      <td><%=aa["name"]%></td>
      <td><%=aa["sex"].to_i==1 ? "男" : "女" %></td>
      <td><%=aa["phone"]%></td>
      <td><%=aa["address"]%></td>
      <td><%=aa["email"]%></td>
      <% if !@activ.column_detail.nil?  %>
        <% cdjs =JSON.parse( @activ.column_detail )%>
        <% cdjs.each do |text_name,label_name| %>
          <td>
          <%=aa[text_name]%>
          </td>
        <% end %>
      <% end %>

      <td>
        <%=aa["admin_content"]%>
      </td>

      <td>

        <a  href="/activities_success?id=<%=aa["id"]%>&activity_id=<%=@activ.id%>" class="btn btn-primary btn-xs"
            style="color:#FFF;" >核准報名</a>

        <a  href="/activities_fail?id=<%=aa["id"]%>&activity_id=<%=@activ.id%>" class="btn btn-danger btn-xs"
            style="color:#FFF;" >取消報名</a>

      </td>

    </tr>
  <% end  %>
  </tbody>
</table>


</div>

app/views/activities/add_a_column.html.erb
<%= form_tag('/store_TableRef', method: :post) do %>

  <style media="screen">
    .form-group label{
      font-size: 20px;
    }
  </style>

    <%= hidden_field_tag :table_name ,@activity.other_table_name %>

    <%= hidden_field_tag :activity_id ,@activity.id %>

    <% @activity.column_num.to_i.times do |ai|
        random_table_name = (0...8).map { (65 + rand(26)).chr }.join
    %>
          <div class="form-group">
            <%= label_tag :title,"欄位名稱#{ai.to_i + 1}" %>
            <%= text_field_tag "field[#{random_table_name}_#{ai.to_i + 1}]" , nil , class: "form-control" %>
          </div>

    <% end  %>

    <div class="form-group">
      <%=submit_tag %>
    </div>

<% end %>

app/views/activities/edit.html.erb
 

<%= render 'form', activity: @activity %>

app/views/activities/excel.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">姓名</Data></Cell>
        <Cell><Data ss:Type="String">姓別</Data></Cell>
        <Cell><Data ss:Type="String">電話</Data></Cell>
        <Cell><Data ss:Type="String">住址</Data></Cell>
        <Cell><Data ss:Type="String">E-Mail</Data></Cell>

        <%
        if !@products.column_detail.nil?
          cdjs = JSON.parse( @products.column_detail )
          cdjs.each do |text_name,label_name|
        %>
          <Cell><Data ss:Type="String">
              <%=label_name%>
            </Data></Cell>
        <% end
        end
        %>

      </Row>
    <% @esult.each do |row| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= row["id"] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= row["name"] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= (row["sex"]==1)? "男" : "女" %></Data></Cell>
        <Cell><Data ss:Type="String"><%= row["phone"] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= row["address"] %></Data></Cell>
        <Cell><Data ss:Type="String"><%= row["email"] %></Data></Cell>
        <%
        if !@products.column_detail.nil?
            cdjs =JSON.parse( @products.column_detail )
            cdjs.each do |text_name,label_name|
        %>
          <Cell>
            <Data ss:Type="String">
              <%=row[text_name]%>
            </Data>
          </Cell>
        <%
          end
        end
        %>


      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/activities/index.html.erb
<% link_to "Excel", excel_path(format: "csv") %>
<% link_to "xls", excel_path(format: "xls") %>

<div class="table-responsive">
  <table class="table table-striped">

  <thead>
    <tr>
      <th>
        <%= sortable "date" ,'日期' %>
      </th>
      <th>
        <%= sortable "time" ,'時間' %>
      </th>
      <th>
        <%= sortable "title" ,'活動名稱' %>
      </th>
      <th>
        <%= sortable "content" ,'活動名稱' %>
      </th>
      <th>
        <%= sortable "limit_user" ,'限制人數' %>
      </th>

      <th colspan="2"><%= link_to '新增活動', new_activity_path  ,class: "btn btn-success"  %></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.date %></td>
        <td><%= activity.time.to_s.split(" ")[1] %></td>
        <td><%= activity.title %></td>
        <td><%= get_str activity.content %></td>
        <td><%= activity.limit_user %>


        </td>

        <td>


          <%
          # if activity.column_num > 0

            t_exist = join_other_table_ok( activity.other_table_name)
            %>
            <% t_exist[0].to_s.length.to_i  %>
            <% activity.other_table_name%>
            <%
              if t_exist[0].to_s.length.to_i < 2
              %>

              <font color="red">資料錯誤</font>

              <% else %>
                <%= link_to '編輯', edit_activity_path(activity) , class: "btn btn-default btn-xs",style: "font-color:#FFF" %>
                <a href="/activities_detial/<%=activity.id%>"
                  class="btn btn-primary btn-xs"
                  style="color:#FFF;" >報名活動人員列表</a>

                  <%= link_to "匯出EXECL", {controller: "activities", action: "excel", id: activity.id ,format: "xls"  }, class: "btn btn-success btn-xs" %>
              <%
              end

            # else
              %>



                <button type="button" id="<%=activity.id%>" name="button"
                  class="btn btn-danger btn-xs" >刪除</button>
              </td>




      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @activities , :theme => 'twitter-bootstrap-3'%>

</div>



<script type="text/javascript">
  $("document").ready(function(){



    $("button").click(function(){
      var r = confirm("確定要刪除嗎 !? ");

      if(r==true){

          // alert(  $(this).attr("id") );

          $.get("/del_activities",{ "id" : $(this).attr("id") },function(data){
                                      // alert(data);


                alert("刪除成功");
                location.reload();


          });

      }else{

      }




    })


  });
</script>

app/views/activities/new.html.erb
<%= render 'form', activity: @activity %>
 

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @activity.time %>
</p>

<p>
  <strong>Title:</strong>
  <%= @activity.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @activity.content %>
</p>

<p>
  <strong>Limit user:</strong>
  <%= @activity.limit_user %>
</p>

<p>
  <strong>Other table name:</strong>
  <%= @activity.other_table_name %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>